/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'bijit' at '11/7/14 2:57 PM' with Gradle 2.1
 *
 * @author bijit, @date 11/7/14 2:57 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
